#!/usr/bin/env ansible-playbook
---
- name: Ubuntu server
  hosts: "{{ custom_hosts | default('servers') }}"
  become: yes
  become_user: root

  tasks:

    - import_role:
        name: dev-box

    - import_role:
        name: docker

    - import_role:
        name: docker-compose-app
